ccflags-y += -Wall -I$(srctree)/kernel/sched
ccflags-y += -I$(srctree)/drivers/misc/motorola/moto_sched

obj-$(CONFIG_MOTO_SCHED) += moto_sched.o

moto_sched-y := msched_main.o msched_sysfs.o msched_common.o

moto_sched-y += locking/locking_main.o
moto_sched-$(CONFIG_MOTO_MUTEX_INHERIT) += locking/mutex.o
moto_sched-$(CONFIG_MOTO_RWSEM_INHERIT) += locking/rwsem.o
moto_sched-$(CONFIG_MOTO_FUTEX_INHERIT) += locking/futex.o
