# SPDX-License-Identifier: GPL-2.0-only
#
# Motorola Backlight drivers
#

obj-$(CONFIG_BACKLIGHT_AW99703)		+= aw99703/
obj-$(CONFIG_BACKLIGHT_KTD3136)		+= ktd3136/
obj-$(CONFIG_BACKLIGHT_LM3697)		+= lm3697/
obj-$(CONFIG_BACKLIGHT_SM5350)		+= sm5350/
