FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
  apt-get install -y --no-install-recommends \
  build-essential \
  bc \
  git \
  wget \
  curl \
  ca-certificates \
  python3 \
  python-is-python3 \
  bison \
  flex \
  libssl-dev \
  libelf-dev \
  rsync \
  file \
  xz-utils \
  cpio \
  libdebuginfod1 \
  gcc-aarch64-linux-gnu \
  libxml2 \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /uniLoader
