# add -Wall to try to catch everything we can.
ccflags-y += -Wall
ccflags-y += -I$(srctree)/drivers/misc/motorola/include
ccflags-y += -I$(srctree)/drivers/base

obj-$(CONFIG_SX9310_TRIPLE) += sx931x_triple.o
