# add -Wall to try to catch everything we can.
ccflags-y += -Wall

ifeq ($(CONFIG_AW_RAMPING_SUPPORT), y)
    ccflags-y += -DCONFIG_AW_RAMPING_SUPPORT
endif

ifeq ($(CONFIG_DUMMY_SND_CARD_SUPPORT), y)
    ccflags-y += -DCONFIG_DUMMY_SND_CARD_SUPPORT
endif

ifeq ($(CONFIG_AW_MTK_RCV_SUPPORT), y)
    ccflags-y += -DCONFIG_AW_MTK_RCV_SUPPORT
endif

aw882xx_dlkm-objs = aw882xx.o aw882xx_bin_parse.o aw882xx_calib.o aw882xx_device.o aw882xx_dsp.o aw882xx_init.o aw882xx_monitor.o aw882xx_spin.o
obj-$(CONFIG_SND_SMARTPA_AW882XX) += aw882xx_dlkm.o
