ccflags-y += -Wall
ccflags-y += -I$(srctree)/drivers/input/touchscreen/focaltech_touch_v3
ccflags-y += -I$(srctree)/drivers/input/touchscreen/focaltech_touch_v3/include
ccflags-y += -I$(srctree)/drivers/input/touchscreen/focaltech_touch_v3/focaltech_test
ccflags-y += -I$(srctree)/drivers/gpu/drm/mediatek/mediatek_v2
ccflags-y += -DCONFIG_INPUT_FOCALTECH_V3_MMI_IC_NAME_FT3681
ccflags-y += -DPRODUCT_MANAUS

obj-$(CONFIG_TOUCHSCREEN_FTS_V3) += focaltech_v3.o
focaltech_v3-objs += focaltech_core.o
focaltech_v3-objs += focaltech_ex_fun.o
focaltech_v3-objs += focaltech_ex_mode.o
focaltech_v3-objs += focaltech_gesture.o
focaltech_v3-objs += focaltech_esdcheck.o
focaltech_v3-objs += focaltech_point_report_check.o
focaltech_v3-objs += focaltech_flash.o
focaltech_v3-objs += focaltech_flash/focaltech_upgrade_ft3681.o
focaltech_v3-objs += focaltech_spi.o
focaltech_v3-objs += focaltech_test/focaltech_test.o
focaltech_v3-objs += focaltech_test/focaltech_test_ini.o
focaltech_v3-objs += focaltech_test/supported_ic/focaltech_test_ft3681.o
focaltech_v3-objs += focaltech_ts_config.o

ifneq ($(filter ft3681,$(CONFIG_INPUT_FOCALTECH_V3_MMI_IC_NAME)),)
	ccflags-y += -DCONFIG_INPUT_FOCALTECH_V3_MMI_IC_NAME_FT3681
endif

ifneq ($(filter m y,$(CONFIG_TOUCHSCREEN_MMI)),)
       ccflags-y += -DCONFIG_INPUT_TOUCHSCREEN_MMI
       focaltech_v3-objs += focaltech_ts_mmi.o
endif
ifneq ($(filter m y,$(CONFIG_INPUT_FOCALTECH_V3_MMI_ENABLE_DOUBLE_TAP)),)
	ccflags-y += -DFOCALTECH_SENSOR_EN
endif
ifneq ($(filter m y,$(CONFIG_INPUT_FOCALTECH_V3_MMI_ENABLE_PALM)),)
	ccflags-y += -DFOCALTECH_PALM_SENSOR_EN
endif
ifneq ($(filter m y,$(CONFIG_INPUT_FOCALTECH_V3_MMI_PEN_NOTIFIER)),)
	ccflags-y += -DFOCALTECH_PEN_NOTIFIER
endif

ifneq ($(filter m y, $(CONFIG_DRM_PANEL_NOTIFICATIONS)),)
	ccflags-y += -DCONFIG_DRM_PANEL_NOTIFICATIONS
endif

ifneq ($(filter m y, $(CONFIG_DRM_PANEL_EVENT_NOTIFICATIONS)),)
	ccflags-y += -DCONFIG_DRM_PANEL_EVENT_NOTIFICATIONS
endif

ifneq ($(filter m y, $(CONFIG_FTS_NOISE_TEST_P2P)),)
	ccflags-y += -DCONFIG_FTS_NOISE_TEST_P2P
endif

ifneq ($(filter m y, $(CONFIG_FTS_COMPATIBLE_WITH_GKI)),)
	ccflags-y += -DCONFIG_FTS_COMPATIBLE_WITH_GKI
endif

ifneq ($(filter m y, $(CONFIG_FTS_DOUBLE_TAP_CONTROL)),)
	ccflags-y += -DCONFIG_FTS_DOUBLE_TAP_CONTROL
endif

ifneq ($(filter m y, $(CONFIG_FTS_SUPPORT_HIGH_RESOLUTION)),)
	ccflags-y += -DCONFIG_FTS_SUPPORT_HIGH_RESOLUTION
endif

ifneq ($(filter m y,$(CONFIG_FTS_LAST_TIME)),)
    ccflags-y += -DCONFIG_FTS_LAST_TIME
endif

ifneq ($(filter m y, $(CONFIG_MTK_PANEL_NOTIFICATIONS)),)
	ccflags-y += -DCONFIG_MTK_PANEL_NOTIFICATIONS
endif

ifneq ($(findstring _factory,$(TARGET_PRODUCT)),)
USE_TARGET_PRODUCT := $(strip $(subst _factory,, $(TARGET_PRODUCT)))
else
USE_TARGET_PRODUCT := $(TARGET_PRODUCT)
endif

ifneq ($(filter aion%, $(USE_TARGET_PRODUCT)), )
	ccflags-y += -DPRODUCT_AION
else ifneq ($(filter manaus%, $(USE_TARGET_PRODUCT)), )
	ccflags-y += -DPRODUCT_MANAUS
endif
