# drivers/misc/mediatek/connectivity/bt/Makefile

# Si se selecciona el soporte para MT6879, entramos en su carpeta
obj-$(CONFIG_MTK_CONN_BT_6879) += mt6879/

# Flags globales para el subsistema de Bluetooth
ccflags-y += -I$(srctree)/drivers/misc/mediatek/connectivity/common/include
ccflags-y += -I$(srctree)/drivers/misc/mediatek/connectivity/bt/include/btif
