# add -Wall to try to catch everything we can.
ccflags-y += -Wall
ccflags-y += -I$(srctree)/drivers/misc/motorola/include

obj-$(CONFIG_MOTO_HALL) += hall_pen.o
obj-$(CONFIG_MOTO_HALL) += hall_folio.o
