# add -Wall to try to catch everything we can.
ccflags-y += -Wall
ccflags-y += -I$(srctree)/drivers/misc/motorola/include
ccflags-y += -I$(srctree)/drivers/base

ifneq ($(filter m y,$(CONFIG_AW9610_MTK_CHARGER)),)
	ccflags-y += -DCONFIG_AW9610_MTK_CHARGER
endif

ifneq ($(filter m y,$(CONFIG_AW9610_MTK_KERNEL419_CHARGER_TYPE)),)
	ccflags-y += -DCONFIG_AW9610_MTK_KERNEL419_CHARGER_TYPE
endif

ifneq ($(filter m y,$(CONFIG_AW9610_MTK_KERNEL5XX_CHARGER_TYPE)),)
	ccflags-y += -DCONFIG_AW9610_MTK_KERNEL5XX_CHARGER_TYPE
endif

obj-$(CONFIG_AW9610X) := aw9610x.o
aw9610x-objs += aw9610x_sar.o
aw9610x-objs += aw_bin_parse.o


