obj-y += isp7_1/
obj-$(CONFIG_VIDEO_MTK_ISP_CAMSYS_7S) += isp7s/
obj-$(CONFIG_VIDEO_MTK_ISP_CAMSYS_7SP) += isp7sp/
obj-$(CONFIG_RPMSG_MTK_CCD) += rpmsg/
obj-$(CONFIG_MTK_CCD_REMOTEPROC) += remoteproc/
