/* SPDX-License-Identifier: GPL-2.0-only */
/* Auto-generated fallback header for missing sysreg feature macros.
 * Generated from arch/arm64/kernel/cpufeature.c plus generated asm/sysreg-defs.h.
 * This is intended for older vendor trees with incomplete asm/sysreg.h. */

#ifndef __ASM_SYSREG_FALLBACKS_H
#define __ASM_SYSREG_FALLBACKS_H

#ifndef DCZID_BS_SHIFT
#define DCZID_BS_SHIFT 0
#endif
#ifndef DCZID_DZP_SHIFT
#define DCZID_DZP_SHIFT 4
#endif
#ifndef ID_AA64DFR0_BRPS_SHIFT
#define ID_AA64DFR0_BRPS_SHIFT 0
#endif
#ifndef ID_AA64DFR0_CTX_CMPS_SHIFT
#define ID_AA64DFR0_CTX_CMPS_SHIFT 0
#endif
#ifndef ID_AA64DFR0_DEBUGVER_SHIFT
#define ID_AA64DFR0_DEBUGVER_SHIFT 0
#endif
#ifndef ID_AA64DFR0_DOUBLELOCK_SHIFT
#define ID_AA64DFR0_DOUBLELOCK_SHIFT 0
#endif
#ifndef ID_AA64DFR0_PMSVER_SHIFT
#define ID_AA64DFR0_PMSVER_SHIFT 0
#endif
#ifndef ID_AA64DFR0_PMUVER_SHIFT
#define ID_AA64DFR0_PMUVER_SHIFT 0
#endif
#ifndef ID_AA64DFR0_WRPS_SHIFT
#define ID_AA64DFR0_WRPS_SHIFT 0
#endif
#ifndef ID_AA64ISAR0_AES_SHIFT
#define ID_AA64ISAR0_AES_SHIFT ID_AA64ISAR0_EL1_AES_SHIFT
#endif
#ifndef ID_AA64ISAR0_ATOMICS_SHIFT
#define ID_AA64ISAR0_ATOMICS_SHIFT 0
#endif
#ifndef ID_AA64ISAR0_CRC32_SHIFT
#define ID_AA64ISAR0_CRC32_SHIFT ID_AA64ISAR0_EL1_CRC32_SHIFT
#endif
#ifndef ID_AA64ISAR0_DP_SHIFT
#define ID_AA64ISAR0_DP_SHIFT ID_AA64ISAR0_EL1_DP_SHIFT
#endif
#ifndef ID_AA64ISAR0_FHM_SHIFT
#define ID_AA64ISAR0_FHM_SHIFT ID_AA64ISAR0_EL1_FHM_SHIFT
#endif
#ifndef ID_AA64ISAR0_RDM_SHIFT
#define ID_AA64ISAR0_RDM_SHIFT ID_AA64ISAR0_EL1_RDM_SHIFT
#endif
#ifndef ID_AA64ISAR0_RNDR_SHIFT
#define ID_AA64ISAR0_RNDR_SHIFT ID_AA64ISAR0_EL1_RNDR_SHIFT
#endif
#ifndef ID_AA64ISAR0_SHA1_SHIFT
#define ID_AA64ISAR0_SHA1_SHIFT ID_AA64ISAR0_EL1_SHA1_SHIFT
#endif
#ifndef ID_AA64ISAR0_SHA2_SHIFT
#define ID_AA64ISAR0_SHA2_SHIFT ID_AA64ISAR0_EL1_SHA2_SHIFT
#endif
#ifndef ID_AA64ISAR0_SHA3_SHIFT
#define ID_AA64ISAR0_SHA3_SHIFT ID_AA64ISAR0_EL1_SHA3_SHIFT
#endif
#ifndef ID_AA64ISAR0_SM3_SHIFT
#define ID_AA64ISAR0_SM3_SHIFT ID_AA64ISAR0_EL1_SM3_SHIFT
#endif
#ifndef ID_AA64ISAR0_SM4_SHIFT
#define ID_AA64ISAR0_SM4_SHIFT ID_AA64ISAR0_EL1_SM4_SHIFT
#endif
#ifndef ID_AA64ISAR0_TLB_SHIFT
#define ID_AA64ISAR0_TLB_SHIFT ID_AA64ISAR0_EL1_TLB_SHIFT
#endif
#ifndef ID_AA64ISAR0_TS_SHIFT
#define ID_AA64ISAR0_TS_SHIFT ID_AA64ISAR0_EL1_TS_SHIFT
#endif
#ifndef ID_AA64ISAR1_APA_ARCHITECTED
#define ID_AA64ISAR1_APA_ARCHITECTED 0
#endif
#ifndef ID_AA64ISAR1_APA_SHIFT
#define ID_AA64ISAR1_APA_SHIFT ID_AA64ISAR1_EL1_APA_SHIFT
#endif
#ifndef ID_AA64ISAR1_API_SHIFT
#define ID_AA64ISAR1_API_SHIFT ID_AA64ISAR1_EL1_API_SHIFT
#endif
#ifndef ID_AA64ISAR1_BF16_SHIFT
#define ID_AA64ISAR1_BF16_SHIFT ID_AA64ISAR1_EL1_BF16_SHIFT
#endif
#ifndef ID_AA64ISAR1_DGH_SHIFT
#define ID_AA64ISAR1_DGH_SHIFT ID_AA64ISAR1_EL1_DGH_SHIFT
#endif
#ifndef ID_AA64ISAR1_DPB_SHIFT
#define ID_AA64ISAR1_DPB_SHIFT ID_AA64ISAR1_EL1_DPB_SHIFT
#endif
#ifndef ID_AA64ISAR1_FCMA_SHIFT
#define ID_AA64ISAR1_FCMA_SHIFT ID_AA64ISAR1_EL1_FCMA_SHIFT
#endif
#ifndef ID_AA64ISAR1_FRINTTS_SHIFT
#define ID_AA64ISAR1_FRINTTS_SHIFT ID_AA64ISAR1_EL1_FRINTTS_SHIFT
#endif
#ifndef ID_AA64ISAR1_GPA_ARCHITECTED
#define ID_AA64ISAR1_GPA_ARCHITECTED 0
#endif
#ifndef ID_AA64ISAR1_GPA_SHIFT
#define ID_AA64ISAR1_GPA_SHIFT ID_AA64ISAR1_EL1_GPA_SHIFT
#endif
#ifndef ID_AA64ISAR1_GPI_SHIFT
#define ID_AA64ISAR1_GPI_SHIFT ID_AA64ISAR1_EL1_GPI_SHIFT
#endif
#ifndef ID_AA64ISAR1_I8MM_SHIFT
#define ID_AA64ISAR1_I8MM_SHIFT ID_AA64ISAR1_EL1_I8MM_SHIFT
#endif
#ifndef ID_AA64ISAR1_JSCVT_SHIFT
#define ID_AA64ISAR1_JSCVT_SHIFT ID_AA64ISAR1_EL1_JSCVT_SHIFT
#endif
#ifndef ID_AA64ISAR1_LRCPC_SHIFT
#define ID_AA64ISAR1_LRCPC_SHIFT ID_AA64ISAR1_EL1_LRCPC_SHIFT
#endif
#ifndef ID_AA64ISAR1_SB_SHIFT
#define ID_AA64ISAR1_SB_SHIFT ID_AA64ISAR1_EL1_SB_SHIFT
#endif
#ifndef ID_AA64ISAR1_SPECRES_SHIFT
#define ID_AA64ISAR1_SPECRES_SHIFT ID_AA64ISAR1_EL1_SPECRES_SHIFT
#endif
#ifndef ID_AA64ISAR2_CLEARBHB_SHIFT
#define ID_AA64ISAR2_CLEARBHB_SHIFT 0
#endif
#ifndef ID_AA64ISAR2_RPRES_SHIFT
#define ID_AA64ISAR2_RPRES_SHIFT ID_AA64ISAR2_EL1_RPRES_SHIFT
#endif
#ifndef ID_AA64ISAR2_WFXT_SHIFT
#define ID_AA64ISAR2_WFXT_SHIFT 0
#endif
#ifndef ID_AA64MMFR0_ASID_SHIFT
#define ID_AA64MMFR0_ASID_SHIFT 0
#endif
#ifndef ID_AA64MMFR0_BIGENDEL0_SHIFT
#define ID_AA64MMFR0_BIGENDEL0_SHIFT ID_AA64MMFR0_EL1_BIGENDEL0_SHIFT
#endif
#ifndef ID_AA64MMFR0_BIGENDEL_SHIFT
#define ID_AA64MMFR0_BIGENDEL_SHIFT 0
#endif
#ifndef ID_AA64MMFR0_ECV_SHIFT
#define ID_AA64MMFR0_ECV_SHIFT ID_AA64MMFR0_EL1_ECV_SHIFT
#endif
#ifndef ID_AA64MMFR0_EXS_SHIFT
#define ID_AA64MMFR0_EXS_SHIFT ID_AA64MMFR0_EL1_EXS_SHIFT
#endif
#ifndef ID_AA64MMFR0_FGT_SHIFT
#define ID_AA64MMFR0_FGT_SHIFT ID_AA64MMFR0_EL1_FGT_SHIFT
#endif
#ifndef ID_AA64MMFR0_PARANGE_SHIFT
#define ID_AA64MMFR0_PARANGE_SHIFT ID_AA64MMFR0_EL1_PARANGE_SHIFT
#endif
#ifndef ID_AA64MMFR0_SNSMEM_SHIFT
#define ID_AA64MMFR0_SNSMEM_SHIFT ID_AA64MMFR0_EL1_SNSMEM_SHIFT
#endif
#ifndef ID_AA64MMFR0_TGRAN16_2_SHIFT
#define ID_AA64MMFR0_TGRAN16_2_SHIFT ID_AA64MMFR0_EL1_TGRAN16_2_SHIFT
#endif
#ifndef ID_AA64MMFR0_TGRAN16_NI
#define ID_AA64MMFR0_TGRAN16_NI ID_AA64MMFR0_EL1_TGRAN16_NI
#endif
#ifndef ID_AA64MMFR0_TGRAN16_SHIFT
#define ID_AA64MMFR0_TGRAN16_SHIFT ID_AA64MMFR0_EL1_TGRAN16_SHIFT
#endif
#ifndef ID_AA64MMFR0_TGRAN4_2_SHIFT
#define ID_AA64MMFR0_TGRAN4_2_SHIFT ID_AA64MMFR0_EL1_TGRAN4_2_SHIFT
#endif
#ifndef ID_AA64MMFR0_TGRAN4_NI
#define ID_AA64MMFR0_TGRAN4_NI ID_AA64MMFR0_EL1_TGRAN4_NI
#endif
#ifndef ID_AA64MMFR0_TGRAN4_SHIFT
#define ID_AA64MMFR0_TGRAN4_SHIFT ID_AA64MMFR0_EL1_TGRAN4_SHIFT
#endif
#ifndef ID_AA64MMFR0_TGRAN64_2_SHIFT
#define ID_AA64MMFR0_TGRAN64_2_SHIFT ID_AA64MMFR0_EL1_TGRAN64_2_SHIFT
#endif
#ifndef ID_AA64MMFR0_TGRAN64_NI
#define ID_AA64MMFR0_TGRAN64_NI ID_AA64MMFR0_EL1_TGRAN64_NI
#endif
#ifndef ID_AA64MMFR0_TGRAN64_SHIFT
#define ID_AA64MMFR0_TGRAN64_SHIFT ID_AA64MMFR0_EL1_TGRAN64_SHIFT
#endif
#ifndef ID_AA64MMFR1_AFP_SHIFT
#define ID_AA64MMFR1_AFP_SHIFT ID_AA64MMFR1_EL1_AFP_SHIFT
#endif
#ifndef ID_AA64MMFR1_ETS_SHIFT
#define ID_AA64MMFR1_ETS_SHIFT ID_AA64MMFR1_EL1_ETS_SHIFT
#endif
#ifndef ID_AA64MMFR1_HADBS_SHIFT
#define ID_AA64MMFR1_HADBS_SHIFT 0
#endif
#ifndef ID_AA64MMFR1_HPD_SHIFT
#define ID_AA64MMFR1_HPD_SHIFT 0
#endif
#ifndef ID_AA64MMFR1_LOR_SHIFT
#define ID_AA64MMFR1_LOR_SHIFT 0
#endif
#ifndef ID_AA64MMFR1_PAN_SHIFT
#define ID_AA64MMFR1_PAN_SHIFT ID_AA64MMFR1_EL1_PAN_SHIFT
#endif
#ifndef ID_AA64MMFR1_SPECSEI_SHIFT
#define ID_AA64MMFR1_SPECSEI_SHIFT 0
#endif
#ifndef ID_AA64MMFR1_TWED_SHIFT
#define ID_AA64MMFR1_TWED_SHIFT ID_AA64MMFR1_EL1_TWED_SHIFT
#endif
#ifndef ID_AA64MMFR1_VHE_SHIFT
#define ID_AA64MMFR1_VHE_SHIFT 0
#endif
#ifndef ID_AA64MMFR1_VMIDBITS_SHIFT
#define ID_AA64MMFR1_VMIDBITS_SHIFT 0
#endif
#ifndef ID_AA64MMFR1_XNX_SHIFT
#define ID_AA64MMFR1_XNX_SHIFT ID_AA64MMFR1_EL1_XNX_SHIFT
#endif
#ifndef ID_AA64MMFR2_AT_SHIFT
#define ID_AA64MMFR2_AT_SHIFT ID_AA64MMFR2_EL1_AT_SHIFT
#endif
#ifndef ID_AA64MMFR2_BBM_SHIFT
#define ID_AA64MMFR2_BBM_SHIFT ID_AA64MMFR2_EL1_BBM_SHIFT
#endif
#ifndef ID_AA64MMFR2_CCIDX_SHIFT
#define ID_AA64MMFR2_CCIDX_SHIFT ID_AA64MMFR2_EL1_CCIDX_SHIFT
#endif
#ifndef ID_AA64MMFR2_CNP_SHIFT
#define ID_AA64MMFR2_CNP_SHIFT 0
#endif
#ifndef ID_AA64MMFR2_E0PD_SHIFT
#define ID_AA64MMFR2_E0PD_SHIFT ID_AA64MMFR2_EL1_E0PD_SHIFT
#endif
#ifndef ID_AA64MMFR2_EVT_SHIFT
#define ID_AA64MMFR2_EVT_SHIFT ID_AA64MMFR2_EL1_EVT_SHIFT
#endif
#ifndef ID_AA64MMFR2_FWB_SHIFT
#define ID_AA64MMFR2_FWB_SHIFT ID_AA64MMFR2_EL1_FWB_SHIFT
#endif
#ifndef ID_AA64MMFR2_IDS_SHIFT
#define ID_AA64MMFR2_IDS_SHIFT ID_AA64MMFR2_EL1_IDS_SHIFT
#endif
#ifndef ID_AA64MMFR2_IESB_SHIFT
#define ID_AA64MMFR2_IESB_SHIFT ID_AA64MMFR2_EL1_IESB_SHIFT
#endif
#ifndef ID_AA64MMFR2_LSM_SHIFT
#define ID_AA64MMFR2_LSM_SHIFT ID_AA64MMFR2_EL1_LSM_SHIFT
#endif
#ifndef ID_AA64MMFR2_LVA_SHIFT
#define ID_AA64MMFR2_LVA_SHIFT 0
#endif
#ifndef ID_AA64MMFR2_NV_SHIFT
#define ID_AA64MMFR2_NV_SHIFT ID_AA64MMFR2_EL1_NV_SHIFT
#endif
#ifndef ID_AA64MMFR2_ST_SHIFT
#define ID_AA64MMFR2_ST_SHIFT ID_AA64MMFR2_EL1_ST_SHIFT
#endif
#ifndef ID_AA64MMFR2_TTL_SHIFT
#define ID_AA64MMFR2_TTL_SHIFT ID_AA64MMFR2_EL1_TTL_SHIFT
#endif
#ifndef ID_AA64MMFR2_UAO_SHIFT
#define ID_AA64MMFR2_UAO_SHIFT ID_AA64MMFR2_EL1_UAO_SHIFT
#endif
#ifndef ID_AA64PFR0_AMU_SHIFT
#define ID_AA64PFR0_AMU_SHIFT ID_AA64PFR0_EL1_AMU_SHIFT
#endif
#ifndef ID_AA64PFR0_ASIMD_NI
#define ID_AA64PFR0_ASIMD_NI 0xf
#endif
#ifndef ID_AA64PFR0_ASIMD_SHIFT
#define ID_AA64PFR0_ASIMD_SHIFT 0
#endif
#ifndef ID_AA64PFR0_CSV2_SHIFT
#define ID_AA64PFR0_CSV2_SHIFT ID_AA64PFR0_EL1_CSV2_SHIFT
#endif
#ifndef ID_AA64PFR0_CSV3_SHIFT
#define ID_AA64PFR0_CSV3_SHIFT ID_AA64PFR0_EL1_CSV3_SHIFT
#endif
#ifndef ID_AA64PFR0_DIT_SHIFT
#define ID_AA64PFR0_DIT_SHIFT ID_AA64PFR0_EL1_DIT_SHIFT
#endif
#ifndef ID_AA64PFR0_EL0_32BIT_64BIT
#define ID_AA64PFR0_EL0_32BIT_64BIT 0
#endif
#ifndef ID_AA64PFR0_EL0_64BIT_ONLY
#define ID_AA64PFR0_EL0_64BIT_ONLY 0
#endif
#ifndef ID_AA64PFR0_EL0_SHIFT
#define ID_AA64PFR0_EL0_SHIFT ID_AA64PFR0_EL1_EL0_SHIFT
#endif
#ifndef ID_AA64PFR0_EL1_32BIT_64BIT
#define ID_AA64PFR0_EL1_32BIT_64BIT 0
#endif
#ifndef ID_AA64PFR0_EL1_64BIT_ONLY
#define ID_AA64PFR0_EL1_64BIT_ONLY 0
#endif
#ifndef ID_AA64PFR0_EL1_SHIFT
#define ID_AA64PFR0_EL1_SHIFT ID_AA64PFR0_EL1_EL1_SHIFT
#endif
#ifndef ID_AA64PFR0_EL2_SHIFT
#define ID_AA64PFR0_EL2_SHIFT ID_AA64PFR0_EL1_EL2_SHIFT
#endif
#ifndef ID_AA64PFR0_EL3_SHIFT
#define ID_AA64PFR0_EL3_SHIFT ID_AA64PFR0_EL1_EL3_SHIFT
#endif
#ifndef ID_AA64PFR0_FP_NI
#define ID_AA64PFR0_FP_NI ID_AA64PFR0_EL1_FP_NI
#endif
#ifndef ID_AA64PFR0_FP_SHIFT
#define ID_AA64PFR0_FP_SHIFT ID_AA64PFR0_EL1_FP_SHIFT
#endif
#ifndef ID_AA64PFR0_GIC_SHIFT
#define ID_AA64PFR0_GIC_SHIFT ID_AA64PFR0_EL1_GIC_SHIFT
#endif
#ifndef ID_AA64PFR0_MPAM_SHIFT
#define ID_AA64PFR0_MPAM_SHIFT ID_AA64PFR0_EL1_MPAM_SHIFT
#endif
#ifndef ID_AA64PFR0_RAS_SHIFT
#define ID_AA64PFR0_RAS_SHIFT ID_AA64PFR0_EL1_RAS_SHIFT
#endif
#ifndef ID_AA64PFR0_SEL2_SHIFT
#define ID_AA64PFR0_SEL2_SHIFT ID_AA64PFR0_EL1_SEL2_SHIFT
#endif
#ifndef ID_AA64PFR0_SVE_SHIFT
#define ID_AA64PFR0_SVE_SHIFT ID_AA64PFR0_EL1_SVE_SHIFT
#endif
#ifndef ID_AA64PFR1_BT_SHIFT
#define ID_AA64PFR1_BT_SHIFT ID_AA64PFR1_EL1_BT_SHIFT
#endif
#ifndef ID_AA64PFR1_MPAMFRAC_SHIFT
#define ID_AA64PFR1_MPAMFRAC_SHIFT 0
#endif
#ifndef ID_AA64PFR1_MTE_NI
#define ID_AA64PFR1_MTE_NI ID_AA64PFR1_EL1_MTE_NI
#endif
#ifndef ID_AA64PFR1_MTE_SHIFT
#define ID_AA64PFR1_MTE_SHIFT ID_AA64PFR1_EL1_MTE_SHIFT
#endif
#ifndef ID_AA64PFR1_RASFRAC_SHIFT
#define ID_AA64PFR1_RASFRAC_SHIFT 0
#endif
#ifndef ID_AA64PFR1_SSBS_PSTATE_NI
#define ID_AA64PFR1_SSBS_PSTATE_NI 0xf
#endif
#ifndef ID_AA64PFR1_SSBS_SHIFT
#define ID_AA64PFR1_SSBS_SHIFT ID_AA64PFR1_EL1_SSBS_SHIFT
#endif
#ifndef ID_AA64ZFR0_AES_SHIFT
#define ID_AA64ZFR0_AES_SHIFT ID_AA64ZFR0_EL1_AES_SHIFT
#endif
#ifndef ID_AA64ZFR0_BF16_SHIFT
#define ID_AA64ZFR0_BF16_SHIFT ID_AA64ZFR0_EL1_BF16_SHIFT
#endif
#ifndef ID_AA64ZFR0_BITPERM_SHIFT
#define ID_AA64ZFR0_BITPERM_SHIFT 0
#endif
#ifndef ID_AA64ZFR0_F32MM_SHIFT
#define ID_AA64ZFR0_F32MM_SHIFT ID_AA64ZFR0_EL1_F32MM_SHIFT
#endif
#ifndef ID_AA64ZFR0_F64MM_SHIFT
#define ID_AA64ZFR0_F64MM_SHIFT ID_AA64ZFR0_EL1_F64MM_SHIFT
#endif
#ifndef ID_AA64ZFR0_I8MM_SHIFT
#define ID_AA64ZFR0_I8MM_SHIFT ID_AA64ZFR0_EL1_I8MM_SHIFT
#endif
#ifndef ID_AA64ZFR0_SHA3_SHIFT
#define ID_AA64ZFR0_SHA3_SHIFT ID_AA64ZFR0_EL1_SHA3_SHIFT
#endif
#ifndef ID_AA64ZFR0_SM4_SHIFT
#define ID_AA64ZFR0_SM4_SHIFT ID_AA64ZFR0_EL1_SM4_SHIFT
#endif
#ifndef ID_AA64ZFR0_SVEVER_SHIFT
#define ID_AA64ZFR0_SVEVER_SHIFT 0
#endif
#ifndef ID_DFR0_COPDBG_SHIFT
#define ID_DFR0_COPDBG_SHIFT 0
#endif
#ifndef ID_DFR0_COPSDBG_SHIFT
#define ID_DFR0_COPSDBG_SHIFT 0
#endif
#ifndef ID_DFR0_COPTRC_SHIFT
#define ID_DFR0_COPTRC_SHIFT 0
#endif
#ifndef ID_DFR0_MMAPDBG_SHIFT
#define ID_DFR0_MMAPDBG_SHIFT 0
#endif
#ifndef ID_DFR0_MMAPTRC_SHIFT
#define ID_DFR0_MMAPTRC_SHIFT 0
#endif
#ifndef ID_DFR0_MPROFDBG_SHIFT
#define ID_DFR0_MPROFDBG_SHIFT 0
#endif
#ifndef ID_DFR0_PERFMON_SHIFT
#define ID_DFR0_PERFMON_SHIFT 0
#endif
#ifndef ID_DFR1_MTPMU_SHIFT
#define ID_DFR1_MTPMU_SHIFT 0
#endif
#ifndef ID_ISAR0_BITCOUNT_SHIFT
#define ID_ISAR0_BITCOUNT_SHIFT 4
#endif
#ifndef ID_ISAR0_BITFIELD_SHIFT
#define ID_ISAR0_BITFIELD_SHIFT 8
#endif
#ifndef ID_ISAR0_CMPBRANCH_SHIFT
#define ID_ISAR0_CMPBRANCH_SHIFT 12
#endif
#ifndef ID_ISAR0_COPROC_SHIFT
#define ID_ISAR0_COPROC_SHIFT 16
#endif
#ifndef ID_ISAR0_DEBUG_SHIFT
#define ID_ISAR0_DEBUG_SHIFT 20
#endif
#ifndef ID_ISAR0_DIVIDE_SHIFT
#define ID_ISAR0_DIVIDE_SHIFT 24
#endif
#ifndef ID_ISAR0_SWAP_SHIFT
#define ID_ISAR0_SWAP_SHIFT 0
#endif
#ifndef ID_ISAR4_BARRIER_SHIFT
#define ID_ISAR4_BARRIER_SHIFT 0
#endif
#ifndef ID_ISAR4_PSR_M_SHIFT
#define ID_ISAR4_PSR_M_SHIFT 0
#endif
#ifndef ID_ISAR4_SMC_SHIFT
#define ID_ISAR4_SMC_SHIFT 0
#endif
#ifndef ID_ISAR4_SWP_FRAC_SHIFT
#define ID_ISAR4_SWP_FRAC_SHIFT 0
#endif
#ifndef ID_ISAR4_SYNCH_PRIM_FRAC_SHIFT
#define ID_ISAR4_SYNCH_PRIM_FRAC_SHIFT 0
#endif
#ifndef ID_ISAR4_UNPRIV_SHIFT
#define ID_ISAR4_UNPRIV_SHIFT 0
#endif
#ifndef ID_ISAR4_WITHSHIFTS_SHIFT
#define ID_ISAR4_WITHSHIFTS_SHIFT 0
#endif
#ifndef ID_ISAR4_WRITEBACK_SHIFT
#define ID_ISAR4_WRITEBACK_SHIFT 0
#endif
#ifndef ID_ISAR5_AES_SHIFT
#define ID_ISAR5_AES_SHIFT 0
#endif
#ifndef ID_ISAR5_CRC32_SHIFT
#define ID_ISAR5_CRC32_SHIFT 0
#endif
#ifndef ID_ISAR5_RDM_SHIFT
#define ID_ISAR5_RDM_SHIFT 0
#endif
#ifndef ID_ISAR5_SEVL_SHIFT
#define ID_ISAR5_SEVL_SHIFT 0
#endif
#ifndef ID_ISAR5_SHA1_SHIFT
#define ID_ISAR5_SHA1_SHIFT 0
#endif
#ifndef ID_ISAR5_SHA2_SHIFT
#define ID_ISAR5_SHA2_SHIFT 0
#endif
#ifndef ID_ISAR6_BF16_SHIFT
#define ID_ISAR6_BF16_SHIFT 0
#endif
#ifndef ID_ISAR6_DP_SHIFT
#define ID_ISAR6_DP_SHIFT 0
#endif
#ifndef ID_ISAR6_FHM_SHIFT
#define ID_ISAR6_FHM_SHIFT 0
#endif
#ifndef ID_ISAR6_I8MM_SHIFT
#define ID_ISAR6_I8MM_SHIFT 0
#endif
#ifndef ID_ISAR6_JSCVT_SHIFT
#define ID_ISAR6_JSCVT_SHIFT 0
#endif
#ifndef ID_ISAR6_SB_SHIFT
#define ID_ISAR6_SB_SHIFT 0
#endif
#ifndef ID_ISAR6_SPECRES_SHIFT
#define ID_ISAR6_SPECRES_SHIFT 0
#endif
#ifndef ID_MMFR0_AUXREG_SHIFT
#define ID_MMFR0_AUXREG_SHIFT 20
#endif
#ifndef ID_MMFR0_FCSE_SHIFT
#define ID_MMFR0_FCSE_SHIFT 24
#endif
#ifndef ID_MMFR0_INNERSHR_SHIFT
#define ID_MMFR0_INNERSHR_SHIFT 28
#endif
#ifndef ID_MMFR0_OUTERSHR_SHIFT
#define ID_MMFR0_OUTERSHR_SHIFT 8
#endif
#ifndef ID_MMFR0_PMSA_SHIFT
#define ID_MMFR0_PMSA_SHIFT 4
#endif
#ifndef ID_MMFR0_SHARELVL_SHIFT
#define ID_MMFR0_SHARELVL_SHIFT 12
#endif
#ifndef ID_MMFR0_TCM_SHIFT
#define ID_MMFR0_TCM_SHIFT 16
#endif
#ifndef ID_MMFR0_VMSA_SHIFT
#define ID_MMFR0_VMSA_SHIFT 0
#endif
#ifndef ID_MMFR4_AC2_SHIFT
#define ID_MMFR4_AC2_SHIFT 0
#endif
#ifndef ID_MMFR4_CCIDX_SHIFT
#define ID_MMFR4_CCIDX_SHIFT 0
#endif
#ifndef ID_MMFR4_CNP_SHIFT
#define ID_MMFR4_CNP_SHIFT 0
#endif
#ifndef ID_MMFR4_EVT_SHIFT
#define ID_MMFR4_EVT_SHIFT 0
#endif
#ifndef ID_MMFR4_HPDS_SHIFT
#define ID_MMFR4_HPDS_SHIFT 0
#endif
#ifndef ID_MMFR4_LSM_SHIFT
#define ID_MMFR4_LSM_SHIFT 0
#endif
#ifndef ID_MMFR4_SPECSEI_SHIFT
#define ID_MMFR4_SPECSEI_SHIFT 0
#endif
#ifndef ID_MMFR4_XNX_SHIFT
#define ID_MMFR4_XNX_SHIFT 0
#endif
#ifndef ID_MMFR5_ETS_SHIFT
#define ID_MMFR5_ETS_SHIFT 0
#endif
#ifndef ID_PFR0_CSV2_SHIFT
#define ID_PFR0_CSV2_SHIFT 0
#endif
#ifndef ID_PFR0_DIT_SHIFT
#define ID_PFR0_DIT_SHIFT 0
#endif
#ifndef ID_PFR0_STATE0_SHIFT
#define ID_PFR0_STATE0_SHIFT 0
#endif
#ifndef ID_PFR0_STATE1_SHIFT
#define ID_PFR0_STATE1_SHIFT 0
#endif
#ifndef ID_PFR0_STATE2_SHIFT
#define ID_PFR0_STATE2_SHIFT 0
#endif
#ifndef ID_PFR0_STATE3_SHIFT
#define ID_PFR0_STATE3_SHIFT 0
#endif
#ifndef ID_PFR1_GENTIMER_SHIFT
#define ID_PFR1_GENTIMER_SHIFT 0
#endif
#ifndef ID_PFR1_GIC_SHIFT
#define ID_PFR1_GIC_SHIFT 0
#endif
#ifndef ID_PFR1_MPROGMOD_SHIFT
#define ID_PFR1_MPROGMOD_SHIFT 0
#endif
#ifndef ID_PFR1_PROGMOD_SHIFT
#define ID_PFR1_PROGMOD_SHIFT 0
#endif
#ifndef ID_PFR1_SECURITY_SHIFT
#define ID_PFR1_SECURITY_SHIFT 0
#endif
#ifndef ID_PFR1_SEC_FRAC_SHIFT
#define ID_PFR1_SEC_FRAC_SHIFT 0
#endif
#ifndef ID_PFR1_VIRTUALIZATION_SHIFT
#define ID_PFR1_VIRTUALIZATION_SHIFT 0
#endif
#ifndef ID_PFR1_VIRT_FRAC_SHIFT
#define ID_PFR1_VIRT_FRAC_SHIFT 0
#endif
#ifndef ID_PFR2_CSV3_SHIFT
#define ID_PFR2_CSV3_SHIFT 0
#endif
#ifndef ID_PFR2_SSBS_SHIFT
#define ID_PFR2_SSBS_SHIFT 0
#endif
#ifndef MVFR0_FPDP_SHIFT
#define MVFR0_FPDP_SHIFT 0
#endif
#ifndef MVFR1_SIMDFMAC_SHIFT
#define MVFR1_SIMDFMAC_SHIFT 0
#endif
#ifndef MVFR1_SIMDINT_SHIFT
#define MVFR1_SIMDINT_SHIFT 0
#endif
#ifndef MVFR1_SIMDLS_SHIFT
#define MVFR1_SIMDLS_SHIFT 0
#endif
#ifndef MVFR1_SIMDSP_SHIFT
#define MVFR1_SIMDSP_SHIFT 0
#endif
#ifndef MVFR2_FPMISC_SHIFT
#define MVFR2_FPMISC_SHIFT 4
#endif
#ifndef MVFR2_SIMDMISC_SHIFT
#define MVFR2_SIMDMISC_SHIFT 0
#endif

/* TRBE register bits (FEAT_TRBE) */
#ifndef TRBLIMITR_ENABLE
#define TRBLIMITR_ENABLE	BIT(0)
#endif

/* GICv3 CPU Interface registers (ICC_*) not generated by tools/sysreg */
#ifndef SYS_ICC_IAR0_EL1
#define SYS_ICC_IAR0_EL1		sys_reg(3, 0, 12, 8, 0)
#endif
#ifndef SYS_ICC_EOIR0_EL1
#define SYS_ICC_EOIR0_EL1		sys_reg(3, 0, 12, 8, 1)
#endif
#ifndef SYS_ICC_HPPIR0_EL1
#define SYS_ICC_HPPIR0_EL1		sys_reg(3, 0, 12, 8, 2)
#endif
#ifndef SYS_ICC_BPR0_EL1
#define SYS_ICC_BPR0_EL1		sys_reg(3, 0, 12, 8, 3)
#endif
#ifndef SYS_ICC_AP0Rn_EL1
#define SYS_ICC_AP0Rn_EL1(n)		sys_reg(3, 0, 12, 8, 4 | (n))
#endif
#ifndef SYS_ICC_AP1Rn_EL1
#define SYS_ICC_AP1Rn_EL1(n)		sys_reg(3, 0, 12, 9, (n))
#endif
#ifndef SYS_ICC_NMIAR1_EL1
#define SYS_ICC_NMIAR1_EL1		sys_reg(3, 0, 12, 9, 5)
#endif
#ifndef SYS_ICC_DIR_EL1
#define SYS_ICC_DIR_EL1			sys_reg(3, 0, 12, 11, 1)
#endif
#ifndef SYS_ICC_SGI1R_EL1
#define SYS_ICC_SGI1R_EL1		sys_reg(3, 0, 12, 11, 5)
#endif
#ifndef SYS_ICC_ASGI1R_EL1
#define SYS_ICC_ASGI1R_EL1		sys_reg(3, 0, 12, 11, 6)
#endif
#ifndef SYS_ICC_SGI0R_EL1
#define SYS_ICC_SGI0R_EL1		sys_reg(3, 0, 12, 11, 7)
#endif
#ifndef SYS_ICC_IAR1_EL1
#define SYS_ICC_IAR1_EL1		sys_reg(3, 0, 12, 12, 0)
#endif
#ifndef SYS_ICC_EOIR1_EL1
#define SYS_ICC_EOIR1_EL1		sys_reg(3, 0, 12, 12, 1)
#endif
#ifndef SYS_ICC_HPPIR1_EL1
#define SYS_ICC_HPPIR1_EL1		sys_reg(3, 0, 12, 12, 2)
#endif
#ifndef SYS_ICC_BPR1_EL1
#define SYS_ICC_BPR1_EL1		sys_reg(3, 0, 12, 12, 3)
#endif
#ifndef SYS_ICC_CTLR_EL1
#define SYS_ICC_CTLR_EL1		sys_reg(3, 0, 12, 12, 4)
#endif
#ifndef SYS_ICC_IGRPEN0_EL1
#define SYS_ICC_IGRPEN0_EL1		sys_reg(3, 0, 12, 12, 6)
#endif
#ifndef SYS_ICC_IGRPEN1_EL1
#define SYS_ICC_IGRPEN1_EL1		sys_reg(3, 0, 12, 12, 7)
#endif
#ifndef SYS_ICC_RPR_EL1
#define SYS_ICC_RPR_EL1			sys_reg(3, 0, 12, 11, 3)
#endif

/* OS Lock register bits (debug) */
#ifndef SYS_OSLSR_OSLK
#define SYS_OSLSR_OSLK			BIT(1)
#endif

/* ID_AA64PFR0_EL1 field values (FEAT_AA64 ELx capability) */
#ifndef ID_AA64PFR0_EL1_ELx_64BIT_ONLY
#define ID_AA64PFR0_EL1_ELx_64BIT_ONLY	0x1
#endif

/* HFGRTR_EL2 / HFGWTR_EL2 fine-grained trap bits (FEAT_FGT, SME/TPIDR2) */
#ifndef HFGxTR_EL2_nSMPRI_EL1_MASK
#define HFGxTR_EL2_nSMPRI_EL1_MASK	BIT(54)
#endif
#ifndef HFGxTR_EL2_nTPIDR2_EL0_MASK
#define HFGxTR_EL2_nTPIDR2_EL0_MASK	BIT(55)
#endif

/* ARM64 ID-register field width (all ID fields are 4-bit nibbles) */
#ifndef ARM64_FEATURE_FIELD_BITS
#define ARM64_FEATURE_FIELD_BITS	4
#endif

/* TRBE ID register bits (FEAT_TRBE) */
#ifndef TRBIDR_PROG
#define TRBIDR_PROG			BIT(0)
#endif

/* Debug system registers not generated by tools/sysreg (EL1 debug) */
#ifndef SYS_MDSCR_EL1
#define SYS_MDSCR_EL1			sys_reg(2, 0, 0, 2, 2)
#endif
#ifndef SYS_OSLAR_EL1
#define SYS_OSLAR_EL1			sys_reg(2, 0, 1, 0, 4)
#endif
#ifndef SYS_OSLSR_EL1
#define SYS_OSLSR_EL1			sys_reg(2, 0, 1, 1, 4)
#endif
#ifndef SYS_DBGBVRn_EL1
#define SYS_DBGBVRn_EL1(n)		sys_reg(2, 0, 0, (n), 4)
#endif
#ifndef SYS_DBGBCRn_EL1
#define SYS_DBGBCRn_EL1(n)		sys_reg(2, 0, 0, (n), 5)
#endif
#ifndef SYS_DBGWVRn_EL1
#define SYS_DBGWVRn_EL1(n)		sys_reg(2, 0, 0, (n), 6)
#endif
#ifndef SYS_DBGWCRn_EL1
#define SYS_DBGWCRn_EL1(n)		sys_reg(2, 0, 0, (n), 7)
#endif

/* Additional debug/RAS registers not generated by tools/sysreg */
#ifndef SYS_OSDLR_EL1
#define SYS_OSDLR_EL1			sys_reg(2, 0, 1, 3, 4)
#endif
#ifndef SYS_ID_AFR0_EL1
#define SYS_ID_AFR0_EL1			sys_reg(3, 0, 0, 1, 3)
#endif
#ifndef SYS_ERRIDR_EL1
#define SYS_ERRIDR_EL1			sys_reg(3, 0, 5, 3, 0)
#endif
#ifndef SYS_ERRSELR_EL1
#define SYS_ERRSELR_EL1			sys_reg(3, 0, 5, 3, 1)
#endif

/* RAS (Reliability, Availability, Serviceability) registers (FEAT_RAS) */
#ifndef SYS_ERXFR_EL1
#define SYS_ERXFR_EL1			sys_reg(3, 0, 5, 4, 0)
#endif
#ifndef SYS_ERXCTLR_EL1
#define SYS_ERXCTLR_EL1		sys_reg(3, 0, 5, 4, 1)
#endif
#ifndef SYS_ERXSTATUS_EL1
#define SYS_ERXSTATUS_EL1		sys_reg(3, 0, 5, 4, 2)
#endif
#ifndef SYS_ERXADDR_EL1
#define SYS_ERXADDR_EL1			sys_reg(3, 0, 5, 4, 3)
#endif
#ifndef SYS_ERXMISC0_EL1
#define SYS_ERXMISC0_EL1		sys_reg(3, 0, 5, 5, 0)
#endif
#ifndef SYS_ERXMISC1_EL1
#define SYS_ERXMISC1_EL1		sys_reg(3, 0, 5, 5, 1)
#endif

/* Physical counter-timer registers (EL0) */
#ifndef SYS_CNTP_TVAL_EL0
#define SYS_CNTP_TVAL_EL0		sys_reg(3, 3, 14, 2, 0)
#endif
#ifndef SYS_CNTP_CTL_EL0
#define SYS_CNTP_CTL_EL0		sys_reg(3, 3, 14, 2, 1)
#endif
#ifndef SYS_CNTP_CVAL_EL0
#define SYS_CNTP_CVAL_EL0		sys_reg(3, 3, 14, 2, 2)
#endif

/* ID_AA64MMFR0_EL1 field values */
#ifndef ID_AA64MMFR0_PARANGE_48
#define ID_AA64MMFR0_PARANGE_48			0x5
#endif
#ifndef ID_AA64MMFR0_TGRAN_2_SUPPORTED_DEFAULT
#define ID_AA64MMFR0_TGRAN_2_SUPPORTED_DEFAULT	0x0
#endif
#ifndef ID_AA64MMFR0_TGRAN_2_SUPPORTED_NONE
#define ID_AA64MMFR0_TGRAN_2_SUPPORTED_NONE	0x1
#endif
#ifndef ID_AA64MMFR0_TGRAN_2_SUPPORTED_MIN
#define ID_AA64MMFR0_TGRAN_2_SUPPORTED_MIN	0x2
#endif
#ifndef ID_AA64MMFR0_TGRAN_2_SUPPORTED_MAX
#define ID_AA64MMFR0_TGRAN_2_SUPPORTED_MAX	0x7
#endif

/* ARM64 feature field mask helper (GENMASK_ULL over 4-bit field at _SHIFT) */
#ifndef ARM64_FEATURE_MASK
#define ARM64_FEATURE_MASK(field)	GENMASK_ULL((field##_SHIFT) + 3, (field##_SHIFT))
#endif

/* ID_DFR0 field values */
#ifndef ID_DFR0_PERFMON_8_4
#define ID_DFR0_PERFMON_8_4		0x5
#endif

/* OSLAR_EL1 register bit */
#ifndef SYS_OSLAR_OSLK
#define SYS_OSLAR_OSLK			BIT(0)
#endif

/* AArch32 counter-timer system register encodings */
#ifndef sys_insn
#define sys_insn			sys_reg
#endif
#ifndef SYS_AARCH32_CNTP_TVAL
#define SYS_AARCH32_CNTP_TVAL		sys_reg(0, 0, 14, 2, 0)
#endif
#ifndef SYS_AARCH32_CNTP_CTL
#define SYS_AARCH32_CNTP_CTL		sys_reg(0, 0, 14, 2, 1)
#endif
#ifndef SYS_AARCH32_CNTP_CVAL
#define SYS_AARCH32_CNTP_CVAL		sys_reg(0, 2, 0, 14, 0)
#endif

/* DC (data cache) instruction encodings used as sysreg descriptors */
#ifndef SYS_DC_ISW
#define SYS_DC_ISW			sys_reg(1, 0, 7, 6, 2)
#endif
#ifndef SYS_DC_CSW
#define SYS_DC_CSW			sys_reg(1, 0, 7, 10, 2)
#endif
#ifndef SYS_DC_CISW
#define SYS_DC_CISW			sys_reg(1, 0, 7, 14, 2)
#endif

/* Additional debug registers */
#ifndef SYS_MDCCINT_EL1
#define SYS_MDCCINT_EL1			sys_reg(2, 0, 0, 2, 0)
#endif
#ifndef SYS_MDRAR_EL1
#define SYS_MDRAR_EL1			sys_reg(2, 0, 1, 0, 0)
#endif
#ifndef SYS_DBGPRCR_EL1
#define SYS_DBGPRCR_EL1			sys_reg(2, 0, 1, 4, 4)
#endif
#ifndef SYS_DBGCLAIMSET_EL1
#define SYS_DBGCLAIMSET_EL1		sys_reg(2, 0, 7, 8, 6)
#endif
#ifndef SYS_DBGCLAIMCLR_EL1
#define SYS_DBGCLAIMCLR_EL1		sys_reg(2, 0, 7, 9, 6)
#endif
#ifndef SYS_DBGAUTHSTATUS_EL1
#define SYS_DBGAUTHSTATUS_EL1		sys_reg(2, 0, 7, 14, 6)
#endif
#ifndef SYS_MDCCSR_EL0
#define SYS_MDCCSR_EL0			sys_reg(2, 3, 0, 1, 0)
#endif

/* OS lock status register bits */
#ifndef SYS_OSLSR_OSLM_IMPLEMENTED
#define SYS_OSLSR_OSLM_IMPLEMENTED	BIT(3)
#endif

#endif /* __ASM_SYSREG_FALLBACKS_H */
