# SPDX-License-Identifier: GPL-2.0
# Copyright (C) 2022 MediaTek Inc.
# C2PS ioctl interface

subdir-ccflags-y += \
	-I$(srctree)/drivers/misc/mediatek/sched/c2ps/common/include/

obj-$(CONFIG_MTK_C2PS) += c2ps_perf_ioctl.o
