ccflags-y += -Wall

ifneq ($(filter m y,$(CONFIG_SX937X_POWER_SUPPLY_ONLINE)),)
    ccflags-y += -DCONFIG_USE_POWER_SUPPLY_ONLINE
endif

ifneq ($(filter m y,$(CONFIG_SX937X_USB_CAL)),)
    ccflags-y += -DCONFIG_CAPSENSE_USB_CAL
endif

ifneq ($(filter m y,$(CONFIG_SX937X_FLIP_CAL)),)
    ccflags-y += -DCONFIG_CAPSENSE_FLIP_CAL
endif

ifneq ($(filter m y,$(CONFIG_SX937X_POWER_CONTROL_SUPPORT)),)
    ccflags-y += -DCONFIG_CAPSENSE_POWER_CONTROL_SUPPORT
endif

ifneq ($(filter m y,$(CONFIG_SX937X_MTK_KERNEL419_CHARGER_TYPE)),)
    ccflags-y += -DCONFIG_SX937X_MTK_KERNEL419_CHARGER_TYPE
endif

ifneq ($(filter m y,$(CONFIG_SX937X_MTK_KERNEL5XX_CHARGER_TYPE)),)
    ccflags-y += -DCONFIG_SX937X_MTK_KERNEL5XX_CHARGER_TYPE
endif

obj-$(CONFIG_MOTO_SX937X_SAR) += sx937x_sar.o

