# SPDX-License-Identifier: GPL-2.0
# Habilitar el soporte de Overlays
DTC_FLAGS += -@

# SoC Base
dtb-$(CONFIG_ARCH_MEDIATEK) += mt6879.dtb

# Dispositivo: Manaus
# Nota: Usamos .dtb porque tus archivos son .dts
dtb-$(CONFIG_ARCH_MEDIATEK) += mt6879-manaus-evb-overlay.dtb
dtb-$(CONFIG_ARCH_MEDIATEK) += mt6879-manaus-dvt1-overlay.dtb
dtb-$(CONFIG_ARCH_MEDIATEK) += mt6879-manaus-dvt2-overlay.dtb
dtb-$(CONFIG_ARCH_MEDIATEK) += mt6879-manaus-dvt1a-overlay.dtb
dtb-$(CONFIG_ARCH_MEDIATEK) += mt6879-manaus-docomo-evt1-overlay.dtb
dtb-$(CONFIG_ARCH_MEDIATEK) += k6879v1_64_manaus.dtb
dtb-$(CONFIG_ARCH_MEDIATEK) += k6879v1_64_manaus_na.dtb
