# SPDX-License-Identifier: GPL-2.0
# Habilitar el soporte de Overlays
DTC_FLAGS += -@

# SoC Base
dtb-$(CONFIG_ARCH_MEDIATEK) += mt6879.dtb

# Dispositivo: Manaus
# Nota: Usamos .dtb porque tus archivos son .dts
dtb-$(CONFIG_ARCH_MEDIATEK) += mt6879-manaus-evb-overlay.dtb
dtb-$(CONFIG_ARCH_MEDIATEK) += mt6879-manaus-dvt1-overlay.dtb
dtb-$(CONFIG_ARCH_MEDIATEK) += mt6879-manaus-dvt2-overlay.dtb
dtb-$(CONFIG_ARCH_MEDIATEK) += mt6879-manaus-dvt1a-overlay.dtb
dtb-$(CONFIG_ARCH_MEDIATEK) += mt6879-manaus-docomo-evt1-overlay.dtb
dtb-$(CONFIG_ARCH_MEDIATEK) += k6879v1_64_manaus.dtb
dtb-$(CONFIG_ARCH_MEDIATEK) += k6879v1_64_manaus_na.dtb

# Resto de SoCs MediaTek
dtb-$(CONFIG_ARCH_MEDIATEK) += mt2712-evb.dtb
dtb-$(CONFIG_ARCH_MEDIATEK) += mt6755-evb.dtb
dtb-$(CONFIG_ARCH_MEDIATEK) += mt6795-evb.dtb
dtb-$(CONFIG_ARCH_MEDIATEK) += mt6797-evb.dtb
dtb-$(CONFIG_ARCH_MEDIATEK) += mt6797-x20-dev.dtb
dtb-$(CONFIG_ARCH_MEDIATEK) += mt6873-evb.dtb
dtb-$(CONFIG_ARCH_MEDIATEK) += mt7622-rfb1.dtb
dtb-$(CONFIG_ARCH_MEDIATEK) += mt7622-bananapi-bpi-r64.dtb
dtb-$(CONFIG_ARCH_MEDIATEK) += mt8173-elm.dtb
dtb-$(CONFIG_ARCH_MEDIATEK) += mt8173-elm-hana.dtb
dtb-$(CONFIG_ARCH_MEDIATEK) += mt8173-elm-hana-rev7.dtb
dtb-$(CONFIG_ARCH_MEDIATEK) += mt8173-evb.dtb
dtb-$(CONFIG_ARCH_MEDIATEK) += mt8183-evb.dtb
dtb-$(CONFIG_ARCH_MEDIATEK) += mt8183-kukui-krane-sku176.dtb
dtb-$(CONFIG_ARCH_MEDIATEK) += mt8516-pumpkin.dtb
