# add -Wall to try to catch everything we can.
ccflags-y += -Wall
ccflags-y += -I$(srctree)/drivers/misc/motorola/include

ifneq ($(filter m y,$(CONFIG_SX933X_MTK_CHARGER)),)
        ccflags-y += -DCONFIG_SX933X_MTK_CHARGER
endif

ifneq ($(filter m y,$(CONFIG_SX933X_MTK_KERNEL419_CHARGER_TYPE)),)
	ccflags-y += -DCONFIG_SX933X_MTK_KERNEL419_CHARGER_TYPE
endif

ifneq ($(filter m y,$(CONFIG_SX933X_USB_CAL)),)
	ccflags-y += -DCONFIG_CAPSENSE_USB_CAL
endif

ifneq ($(filter m y,$(CONFIG_SX933X_FLIP_CAL)),)
	ccflags-y += -DCONFIG_CAPSENSE_FLIP_CAL
endif

ifneq (,$(filter river%,$(TARGET_PRODUCT)))
ccflags-y += -DCONFIG_CAPSENSE_USB_CAL
endif

ifneq (,$(filter doha%,$(TARGET_PRODUCT)))
ccflags-y += -DCONFIG_CAPSENSE_USB_CAL
endif

ifneq (,$(filter sofia%,$(TARGET_PRODUCT)))
ccflags-y += -DCONFIG_CAPSENSE_USB_CAL
endif

ifneq (,$(filter odin%,$(TARGET_PRODUCT)))
ccflags-y += -DCONFIG_CAPSENSE_USB_CAL \
		-DCONFIG_CAPSENSE_ATTACH_CAL
endif

ifneq (,$(filter olson%,$(TARGET_PRODUCT)))
ccflags-y += -DCONFIG_CAPSENSE_USB_CAL \
		-DCONFIG_CAPSENSE_FLIP_CAL
endif

ifneq (,$(filter rav%,$(TARGET_PRODUCT)))
ccflags-y += -DCONFIG_CAPSENSE_USB_CAL
endif

ifneq (,$(filter burton%,$(TARGET_PRODUCT)))
ccflags-y += -DCONFIG_CAPSENSE_USB_CAL
endif

ifneq (,$(filter smith% nairo%,$(TARGET_PRODUCT)))
ccflags-y += -DCONFIG_CAPSENSE_USB_CAL
endif

ifneq (,$(filter racer%,$(TARGET_PRODUCT)))
ccflags-y += -DCONFIG_CAPSENSE_USB_CAL
ccflags-y += -DCONFIG_CAPSENSE_HEADSET_STATE
endif

ifneq (,$(filter kiev%,$(TARGET_PRODUCT)))
ccflags-y += -DCONFIG_CAPSENSE_USB_CAL
endif

ccflags-y += -I$(srctree)/drivers/base

obj-$(CONFIG_SX933X_SAR) += sx933x_sar.o
