# add -Wall to try to catch everything we can.
ccflags-y += -Wall
ccflags-y += -I$(srctree)/drivers/misc/motorola/include

ifeq ($(filter m y, $(CONFIG_INPUT_DRV2624_HAPTICS)),)
obj-$(CONFIG_DRV2624_MMI) += drv2624_mmi.o
endif
